In [11]:
#import numpy library
import numpy as np

x = np.array(["A",45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

['A' '45' '67' '57' '60']
<class 'numpy.ndarray'>
<U11


In [5]:
import numpy as np

x = np.array([45,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

[45.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [17]:
import numpy as np

x = np.array([["A",67],[57,9.8]])
print(x)
print(type(x))
print(x.dtype)

[['A' '67']
 ['57' '9.8']]
<class 'numpy.ndarray'>
<U32


In [19]:
print(x.shape)

(2, 2)


In [31]:
x = np.array([45,67,57,98])
y = x.reshape(4,1)
print(y)
print(y.shape)


[[45]
 [67]
 [57]
 [98]]
(4, 1)


In [37]:
z = np.arange(3,10)
print(z)
type(z)

[3 4 5 6 7 8 9]


numpy.ndarray

In [43]:
a = np.array([1.3692,2.3692,3.3692])
print(a)
np.around(a,2)

[1.3692 2.3692 3.3692]


array([1.37, 2.37, 3.37])

In [49]:
a = np.array([1.3692,2.3692,3.3692])
print(a)
print(np.around(np.sqrt(a),2))

[1.3692 2.3692 3.3692]
[1.17 1.54 1.84]


In [57]:
x = np.array([[3,67],[57,np.NAN]])
print(x)


[[ 3. 67.]
 [57. nan]]


In [63]:
a1_copy1 = x.astype(str)
print(a1_copy1)
a1_copy1.dtype



[['3.0' '67.0']
 ['57.0' 'nan']]


dtype('<U32')

In [70]:
z.dtype

dtype('int32')

In [76]:
x = np.array([[3,67],[4,6],[57,9]])
x

array([[ 3, 67],
       [ 4,  6],
       [57,  9]])

In [80]:
print(x.sum(axis = 1))

[70 10 66]


In [82]:
x = np.array([[3,67],[4,6],[57,9]])
print(x)
np.fill_diagonal(x,0)
print(x)

[[ 3 67]
 [ 4  6]
 [57  9]]
[[ 0 67]
 [ 4  0]
 [57  9]]


In [90]:
x = np.array([[3,67],[4,6],[57,9]])
y = np.array([[3,67],[4,6],[57,9]])

print(x.T)
print(y.T)


[[ 3  4 57]
 [67  6  9]]
[[ 3  4 57]
 [67  6  9]]


In [94]:
c = np.array([[3,67],[4,6],[4,6],[57,9]])
c

array([[ 3, 67],
       [ 4,  6],
       [ 4,  6],
       [57,  9]])

In [96]:
c[1][1]

6